name: HavenHold
version: '1.0-BETA'
main: me.ferzic.havenHold.HavenHold
api-version: '1.21'
authors: [ Ferzic, Geoh ]
description: The core plugin of Haven Hold Network.
commands:
  core:
    description: Main command for HavenHold.
    usage: /<command> <param>
    aliases: [c, hh]
permissions:
  havenhold.use:
    description: Allows use of HavenHold commands.
    default: op